---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: default-lb
spec:
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/worker
        operator: DoesNotExist
  externalIPs: true
  loadBalancerIPs: true
---
apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool
metadata:
  name: default-lb-ipam
spec:
  blocks:
    - start: 192.168.1.5
      stop: 192.168.1.20
    - start: 192.169.1.30
      stop: 192.168.1.50
