---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      chart: cilium
      version: '1.18.6'
      sourceRef:
        kind: HelmRepository
        name: cilium-helm
        namespace: kube-system
      interval: 10m
  values:
    hubble:
      tls:
        auto:
          enabled: true
          method: cronJob
          certValidDuration: 1095
          schedule: 0 0 1 */4 *
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
    ingressController:
      enabled: false
      default: false
    egressGateway:
      enabled: true
    bpf:
      masquerade: true
    kubeProxyReplacement: true
