---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics
  namespace: o11y
spec:
  interval: 10m
  chart:
    spec:
      chart: victoria-metrics-single
      version: '0.31.0'
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics-helm
        namespace: o11y
      interval: 10m
  values:
