---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics
  namespace: o11y
spec:
  interval: 10m
  chart:
    spec:
      chart: victoria-metrics-single
      version: '0.31.0'
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics-helm
        namespace: o11y
      interval: 10m
  values:
    server:
      enabled: true
      name: victoria-metrics-single
      replicaCount: 1
      extraArgs:
        envflag.enable: true
        envflag.prefix: VM_
        loggerFormat: json
        httpListenAddr: :8428

      # -- Env vaiables
      # -- Additional environment variables (ex.: secret tokens, flags). Check [here](https://docs.victoriametrics.com/victoriametrics/#environment-variables) for more details
      env: []

      # -- Specify alternative source for env variables
      envFrom: []
        #- configMapRef:
        #    name: special-config

      persistentVolume:
        # -- Create/use Persistent Volume Claim for server component. Empty dir if false
        enabled: true
