---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-exporter
  namespace: node-exporter
spec:
  chartRef:
    kind: OCIRepository
    name: node-exporter-helm
  interval: 10m
  values:
