---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metrics-server-helm
  namespace: kube-system
spec:
  interval: 1m0s
  url: https://kubernetes-sigs.github.io/metrics-server
