---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      chart: plex-media-server
      version: '1.4.0'
      sourceRef:
        kind: HelmRepository
        name: plex-helm
        namespace: media-server
      interval: 10m
  values:
    ingress:
      enabled: true
      url: https://plex.k8s.deep-thonk.com
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
    pms:
      configStorage: 10Gi
