---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 10m
  chart:
    spec:
      chart: vault
      version: '4.12.0'
      sourceRef:
        kind: HelmRepository
        name: hashicorp-helm
        namespace: vault
      interval: 10m
