---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      chart: metallb
      version: '0.15.3'
      sourceRef:
        kind: HelmRepository
        name: metallb-helm
        namespace: kube-system
      interval: 10m
