---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 10m
  chart:
    spec:
      chart: external-secrets-helm
      version: '2.0.0'
      sourceRef:
        kind: HelmRepository
        name: external-secrets-helm
        namespace: kube-system
      interval: 10m
