---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 10m
  chart:
    spec:
      chart: vault
      version: '0.32.0'
      sourceRef:
        kind: HelmRepository
        name: vault-helm
        namespace: vault
      interval: 10m
  values:
    global:
      enabled: true
      tlsDisable: true
    server:
      standalone:
        enabled: true
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-staging"
        hosts:
          - host: vault.k8s.deep-thonk.com
            extraPaths:
              - path: /*
                pathType: Prefix
                backend:
                  service:
                    name: vault-ui
                    port:
                      number: 8200
        tls:
          - secretName: vault-tls
            hosts:
              - vault.k8s.deep-thonk.com
    ui:
      enabled: true
      serviceType: "ClusterIP"
