---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: o11y
spec:
  interval: 10m
  chart:
    spec:
      chart: loki
      version: '6.52.0'
      sourceRef:
        kind: HelmRepository
        name: grafana-helm
        namespace: o11y
      interval: 10m
  values:
    loki:
      commonConfig:
        replication_factor: 1
      schemaConfig:
        configs:
          - from: "2024-04-01"
            store: tsdb
            object_store: s3
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
      podSecurityContext:
        fsGroup: 65534
        runAsGroup: 65534
        runAsUser: 65534
      storage_config:
        aws:
          region: garage
          bucketnames: observability
          s3forcepathstyle: false
      pattern_ingester:
          enabled: true
      limits_config:
        allow_structured_metadata: true
        volume_enabled: true
        retention_period: 672h # 28 days retention

      storage:
        type: s3
        bucketNames:
          chunks: observability
          ruler: observability
          admin: observability
        s3:
          endpoint: ${OBSERVABILITY_S3_ENDPOINT}
          region: garage
          secretAccessKey: ${OBSERVABILITY_S3_ACCESS_KEY}
          accessKeyId: ${OBSERVABILITY_S3_SECRET_KEY}
      ruler:
        enable_api: true
      auth_enabled: false

    # Disable minio storage
    minio:
        enabled: false


    deploymentMode: SingleBinary

    singleBinary:
      replicas: 2
      resource:
        requests:
          cpu: "100m"
          memory: "2Gi"
        limits:
          cpu: "200m"
          memory: "4Gi"
      persistance:
        storageClass: gp2
        accessModes:
          - ReadWriteOnce
        size: 30Gi


    global:
      dnsService: coredns
      extraArgs:
        - config.expand-env=true
      extraEnv:
        - name: OBSERVABILITY_S3_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: endpoint
        - name: OBSERVABILITY_S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: access_key
        - name: OBSERVABILITY_S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: secret_key

    sidecar:
      image:
        repository: kiwigrid/k8s-sidecar
        tag: 1.30.0
      resources:
        requests:
          cpu: 50m
          memory: 50Mi
        limits:
          cpu: 100m
          memory: 100Mi


    # Zero out replica counts of other deployment modes
    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0

    ingester:
      replicas: 0
    querier:
      replicas: 0
    queryFrontend:
      replicas: 0
    queryScheduler:
      replicas: 0
    distributor:
      replicas: 0
    compactor:
      replicas: 0
    indexGateway:
      replicas: 0
    bloomCompactor:
      replicas: 0
    bloomGateway:
      replicas: 0
