---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
  namespace: o11y
spec:
  interval: 10m
  chart:
    spec:
      chart: alloy
      version: '1.6.0'
      sourceRef:
        kind: HelmRepository
        name: grafana-helm
        namespace: o11y
      interval: 10m
  values:
    alloy:
      configMap:
        # -- Create a new ConfigMap for the config file.
        create: true
        # -- Content to assign to the new ConfigMap.  This is passed into `tpl` allowing for templating from values.
        content: ''

      # -- Path to where Grafana Alloy stores data (for example, the Write-Ahead Log).
      # By default, data is lost between reboots.
      storagePath: /tmp/alloy

      # -- Enables Grafana Alloy container's http server port.
      enableHttpServerPort: true

      # -- Address to listen for traffic on. 0.0.0.0 exposes the UI to other
      # containers.
      listenAddr: 0.0.0.0

      # -- Port to listen for traffic on.
      listenPort: 12345

      # -- Scheme is needed for readiness probes. If enabling tls in your configs, set to "HTTPS"
      listenScheme: HTTP

      # -- Initial delay for readiness probe.
      initialDelaySeconds: 10

      # -- Timeout for readiness probe.
      timeoutSeconds: 1

      # --  Base path where the UI is exposed.
      uiPathPrefix: /

      # -- Enables sending Grafana Labs anonymous usage stats to help improve Grafana
      # Alloy.
      enableReporting: false

      # -- Extra environment variables to pass to the Alloy container.
      extraEnv: []

      # -- Maps all the keys on a ConfigMap or Secret as environment variables. https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#envfromsource-v1-core
      envFrom: []

      # -- Extra args to pass to `alloy run`: https://grafana.com/docs/alloy/latest/reference/cli/run/
      extraArgs: []

      # -- Extra ports to expose on the Alloy container.
      extraPorts: []
      # - name: "faro"
      #   port: 12347
      #   targetPort: 12347
      #   protocol: "TCP"
      #   appProtocol: "h2c"

      # -- Host aliases to add to the Alloy container.
      hostAliases: []
      # - ip: "20.21.22.23"
      #   hostnames:
      #     - "company.grafana.net"

      # -- Security context to apply to the Grafana Alloy container.
      securityContext: {}

      # -- Resource requests and limits to apply to the Grafana Alloy container.
      resources: {}

    image:
      # -- Grafana Alloy image registry (defaults to docker.io)
      registry: "docker.io"
      # -- Grafana Alloy image repository.
      repository: grafana/alloy
      # -- (string) Grafana Alloy image tag. When empty, the Chart's appVersion is
      # used.
      tag: null
      pullPolicy: IfNotPresent

    rbac:
      create: true

      # -- The rules to create for the ClusterRole or Role objects.
      rules:
        # -- Rules required for the `discovery.kubernetes` component.
        - apiGroups: ["", "discovery.k8s.io", "networking.k8s.io"]
          resources: ["endpoints", "endpointslices", "ingresses", "pods", "services"]
          verbs: ["get", "list", "watch"]
        # -- Rules required for the `loki.source.kubernetes` component.
        - apiGroups: [""]
          resources: ["pods", "pods/log", "namespaces"]
          verbs: ["get", "list", "watch"]
        # -- Rules required for the `loki.source.podlogs` component.
        - apiGroups: ["monitoring.grafana.com"]
          resources: ["podlogs"]
          verbs: ["get", "list", "watch"]
        # -- Rules required for the `mimir.rules.kubernetes` component.
        - apiGroups: ["monitoring.coreos.com"]
          resources: ["prometheusrules"]
          verbs: ["get", "list", "watch"]
        # -- Rules required for the `mimir.alerts.kubernetes` component.
        - apiGroups: ["monitoring.coreos.com"]
          resources: ["alertmanagerconfigs"]
          verbs: ["get", "list", "watch"]
        # -- Rules required for the `prometheus.operator.*` components.
        - apiGroups: ["monitoring.coreos.com"]
          resources: ["podmonitors", "servicemonitors", "probes", "scrapeconfigs"]
          verbs: ["get", "list", "watch"]
        # -- Rules required for the `loki.source.kubernetes_events` component.
        - apiGroups: [""]
          resources: ["events"]
          verbs: ["get", "list", "watch"]
        # -- Rules required for the `remote.kubernetes.*` components.
        - apiGroups: [""]
          resources: ["configmaps", "secrets"]
          verbs: ["get", "list", "watch"]
        # -- Rules required for the `otelcol.processor.k8sattributes` component.
        - apiGroups: ["apps", "extensions"]
          resources: ["replicasets"]
          verbs: ["get", "list", "watch"]

      # -- The rules to create for the ClusterRole objects.
      clusterRules:
        # -- Rules required for the Nodes role in the `discovery.kubernetes` component.
        - apiGroups: [""]
          resources: ["nodes"]
          verbs: ["get", "list", "watch"]
        # -- Rules required for the `discovery.kubelet` component.
        - apiGroups: [""]
          resources: ["nodes/pods"]
          verbs: ["get", "list", "watch"]
        # -- Rules required accessing metric endpoints on the Node (e.g. Kubelet, cAdvisor, etc...).
        - apiGroups: [""]
          resources: ["nodes/metrics"]
          verbs: ["get", "list", "watch"]
        # -- Rules required for accessing metrics endpoint.
        - nonResourceURLs: ["/metrics"]
          verbs: ["get"]

    serviceAccount:
      create: true
      additionalLabels: {}
      annotations: {}

    # Options for the extra controller used for config reloading.
    configReloader:
      enabled: true
      image:
        # -- Config reloader image registry (defaults to docker.io)
        registry: "quay.io"
        # -- Repository to get config reloader image from.
        repository: prometheus-operator/prometheus-config-reloader
        # -- Tag of image to use for config reloading.
        tag: v0.81.0
        # -- SHA256 digest of image to use for config reloading (either in format "sha256:XYZ" or "XYZ"). When set, will override `configReloader.image.tag`
        digest: ""
      # -- Override the args passed to the container.
      customArgs: []
      # -- Resource requests and limits to apply to the config reloader container.
      resources:
        requests:
          cpu: "10m"
          memory: "50Mi"
      # -- Security context to apply to the Grafana configReloader container.
      securityContext: {}

    controller:
      type: 'daemonset'
      extraLabels: {}
      extraAnnotations: {}
      # -- How many additional seconds to wait before considering a pod ready.
      minReadySeconds: 10

      # -- Configures Pods to use the host network. When set to true, the ports that will be used must be specified.
      hostNetwork: false

      # -- Configures Pods to use the host PID namespace.
      hostPID: false

      # -- Configures the DNS policy for the pod. https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy
      dnsPolicy: ClusterFirst

      # -- Termination grace period in seconds for the Grafana Alloy pods.
      # The default value used by Kubernetes if unspecifed is 30 seconds.
      terminationGracePeriodSeconds: null

      # -- Update strategy for updating deployed Pods.
      updateStrategy: {}

      # -- nodeSelector to apply to Grafana Alloy pods.
      nodeSelector: {}

      # -- Tolerations to apply to Grafana Alloy pods.
      tolerations: []

      # -- Topology Spread Constraints to apply to Grafana Alloy pods.
      topologySpreadConstraints: []

      # -- priorityClassName to apply to Grafana Alloy pods.
      priorityClassName: ''

      # -- Extra pod annotations to add.
      podAnnotations: {}

      # -- Extra pod labels to add.
      podLabels: {}

      # -- PodDisruptionBudget configuration.
      podDisruptionBudget:
        # -- Whether to create a PodDisruptionBudget for the controller.
        enabled: false
        # -- Minimum number of pods that must be available during a disruption.
        # Note: Only one of minAvailable or maxUnavailable should be set.
        minAvailable: null
        # -- Maximum number of pods that can be unavailable during a disruption.
        # Note: Only one of minAvailable or maxUnavailable should be set.
        maxUnavailable: null

      # -- Whether to enable automatic deletion of stale PVCs due to a scale down operation, when controller.type is 'statefulset'.
      enableStatefulSetAutoDeletePVC: false

      # -- Affinity configuration for pods.
      affinity: {}

      volumes:
        # -- Extra volumes to add to the Grafana Alloy pod.
        extra: []

      # -- volumeClaimTemplates to add when controller.type is 'statefulset'.
      volumeClaimTemplates: []

      ## -- Additional init containers to run.
      ## ref: https://kubernetes.io/docs/concepts/workloads/pods/init-containers/
      ##
      initContainers: []

      # -- Additional containers to run alongside the Alloy container and initContainers.
      extraContainers: []

    service:
      enabled: true
      type: ClusterIP
      internalTrafficPolicy: Cluster
      annotations: {}
        # cloud.google.com/load-balancer-type: Internal

    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      labels: {}
      path: /
      faroPort: 12347

      pathType: Prefix

      hosts:
        - alloy.k8s.deep-thonk.com
      extraPaths: []

      tls: 
        - secretName: alloy-tls
          hosts:
            - alloy.k8s.deep-thonk.com

    extraObjects: []
    # - apiVersion: v1
    #   kind: Secret
    #   metadata:
    #     name: grafana-cloud
    #   stringData:
    #     PROMETHEUS_HOST: 'https://prometheus-us-central1.grafana.net/api/prom/push'
    #     PROMETHEUS_USERNAME: '123456'
