---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: o11y
spec:
  interval: 10m
  chart:
    spec:
      chart: loki
      version: '6.52.0'
      sourceRef:
        kind: HelmRepository
        name: grafana-helm
        namespace: o11y
      interval: 10m
  values:
    global:
      dnsService: coredns
      extraArgs:
        - config.expand-env=true
      extraEnv:
        - name: OBSERVABILITY_S3_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: endpoint
        - name: OBSERVABILITY_S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: access_key
        - name: OBSERVABILITY_S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: secret_key
    loki:
      schemaConfig:
        configs:
          - from: 2024-04-01
            store: tsdb
            object_store: s3
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
      storage_config:
        aws:
          region: garage
          bucketnames: observability
          s3forcepathstyle: false
      ingester:
          chunk_encoding: snappy
      pattern_ingester:
          enabled: true
      limits_config:
        allow_structured_metadata: true
        volume_enabled: true
        retention_period: 672h # 28 days retention
      querier:
          max_concurrent: 4

      storage:
        type: s3
        bucketNames:
          chunks: observability
          ruler: observability
          admin: observability
        s3:
          endpoint: ${OBSERVABILITY_S3_ENDPOINT}
          region: garage
          secretAccessKey: ${OBSERVABILITY_S3_ACCESS_KEY}
          accessKeyId: ${OBSERVABILITY_S3_SECRET_KEY}

    deploymentMode: Distributed

    # Disable minio storage
    minio:
        enabled: false

    ingester:
      replicas: 3
      zoneAwareReplication:
        enabled: false
    querier:
      replicas: 2
      maxUnavailable: 2
    queryFrontend:
      replicas: 2
      maxUnavailable: 1
    queryScheduler:
      replicas: 2
    distributor:
      replicas: 2
      maxUnavailable: 2
    compactor:
      replicas: 1
    indexGateway:
      replicas: 2
      maxUnavailable: 1

    bloomPlanner:
      replicas: 0
    bloomBuilder:
      replicas: 0
    bloomGateway:
      replicas: 0

    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0

    singleBinary:
      replicas: 0
