---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: applications
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure
  interval: 10m0s
  path: infrastructure/deep-thonk
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
