---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: storage-hostpath-mount
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: microk8s.io/hostpath
reclaimPolicy: Delete
parameters:
  pvDir: /mnt/plex/k8s
volumeBindingMode: WaitForFirstConsumer
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: storage-hostpath-root
provisioner: microk8s.io/hostpath
reclaimPolicy: Delete
parameters:
  pvDir: /opt/store
volumeBindingMode: WaitForFirstConsumer
