---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: infisical
  namespace: infisical
spec:
  interval: 10m
  chart:
    spec:
      chart: infisical
      version: '0.4.2'
      sourceRef:
        kind: HelmRepository
        name: infisical-helm
        namespace: infisical
      interval: 10m
  values:
    infisical:
      image:
        repository: infisical/infisical
        tag: "v0.151.0"
        pullPolicy: IfNotPresent
      replicaCount: 2

    ingress:
      enabled: true
      hostName: infisical.k8s.deep-thonk.com
