---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: infisical-helm
  namespace: infisical
spec:
  interval: 1m0s
  url: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts
