apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  finalizers:
  - finalizers.fluxcd.io
  generation: 1
  name: jetstack
  namespace: flux-system
spec:
  interval: 1m0s
  provider: generic
  url: https://charts.jetstack.io
