---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: cert-manager-helm
  interval: 10m
  values:
    storageClasses:
      - name: nfs-retain
        annotations:
          storageclass.kubernetes.io/is-default-class: "true"
        parameters:
          server: deep-thonk.com
          share: /mnt/plex/k8s
        reclaimPolicy: Retain
        volumeBindingMode: Immediate
        mountOptions:
          - nfsvers=4.1
