---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cert-manager-helm
  namespace: cert-manager
spec:
  interval: 1m0s
  url: oci://quay.io/jetstack/charts/cert-manager
  ref:
    semver: ">=0.0.0-0"
