apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: ingress-system
spec:
  chart:
    spec:
      chart: metallb
      version: 0.13.7
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: metallb
  ---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-addr-pool
  namespace: ingress-system
spec:
  addresses:
    - 192.168.2.0/25
