---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: observability
spec:
  interval: 10m
  chart:
    spec:
      chart: grafana
      version: '10.5.15'
      sourceRef:
        kind: HelmRepository
        name: grafana-helm
        namespace: observability
      interval: 10m
  values:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/clusterissuer: "letsencrypt-staging"
      hosts:
        - grafana.k8s.deep-thonk.com
      tls:
        - secretName: grafana-tls
          hosts:
            - grafana.k8s.deep-thonk.com
